=== ViktorEdfalk/common/ts-diabetes/src/main/resources/schemas/transport_model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2013 Inera AB (http://www.inera.se) This file is part 
  of Inera Certificate Modules (http://code.google.com/p/inera-certificate-modules). 
  Inera Certificate Modules is free software: you can redistribute it and/or 
  modify it under the terms of the GNU Affero General Public License as published 
  by the Free Software Foundation, either version 3 of the License, or (at 
  your option) any later version. Inera Certificate Modules is distributed 
  in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even 
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
  See the GNU Affero General Public License for more details. You should have 
  received a copy of the GNU Affero General Public License along with this 
  program. If not, see <http://www.gnu.org/licenses/>. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="urn:riv:clinicalprocess:healthcond:certificate:1"
  xmlns:extension="urn:intyg:ts-diabetes:model:ext:1" xmlns:iso="urn:iso:21090:dt:1"
  targetNamespace="urn:riv:clinicalprocess:healthcond:certificate:1"
  elementFormDefault="qualified" attributeFormDefault="unqualified"
  version="1.0">

  <xs:import namespace="urn:iso:21090:dt:1" schemaLocation="core_components/iso_dt_subset_1.0.xsd" />

  <xs:element name="utlatande" type="utlatandeType" />

  <xs:complexType name="utlatandeType">
    <xs:sequence>
      <xs:element name="utlatande-id" type="utlatandeId" />
      <xs:element name="typAvUtlatande" type="utlatandeTyp" />
      <xs:element name="kommentar" type="xs:string"
        minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="signeringsdatum" type="dateTime" />
      <xs:element name="skickatdatum" type="dateTime"
        minOccurs="0" />
      <xs:element name="intygAvser" type="iso:CD" maxOccurs="unbounded" />


      <xs:element name="patient" type="patientType" />
      <xs:element name="skapadAv" type="hosPersonalType" />

      <xs:element name="vardkontakt" type="vardkontaktType" />
      <xs:element name="aktivitet" type="aktivitetType"
        minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="rekommendation" type="rekommendationType"
        minOccurs="1" maxOccurs="3" />
      <xs:element name="observation" type="observationType"
        maxOccurs="unbounded" />
      <xs:element name="observationAktivitetRelation" type="observationAktivitetRelationType"
        minOccurs="0" maxOccurs="unbounded" />

      <xs:element name="bilaga" type="bilagaType" minOccurs="1"
        maxOccurs="1" />
      <xs:element name="utgava" type="xs:string" />
      <xs:element name="version" type="xs:string" />


      <xs:any namespace="##other" processContents="lax"
        minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="utlatandeId">
    <xs:complexContent>
      <xs:restriction base="iso:II">
        <xs:attribute name="root" type="iso:Uid" use="required" />
        <xs:attribute name="extension" type="xs:string"
          use="optional" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="utlatandeTyp">
    <xs:complexContent>
      <xs:restriction base="iso:CD">
        <xs:attribute name="code" type="xs:string" use="required" />
        <xs:attribute name="codeSystem" type="iso:Uid" use="required"
          fixed="f6fb361a-e31d-48b8-8657-99b63912dd9b" />
        <xs:attribute name="codeSystemName" type="xs:string"
          use="required" fixed="kv_utlåtandetyp_intyg" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="personId">
    <xs:complexContent>
      <xs:restriction base="iso:II">
        <xs:attribute name="root" type="patientIdRoot" use="required" />
        <xs:attribute name="extension" type="patientIdExtension"
          use="required" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="patientIdRoot">
    <xs:restriction base="iso:Uid">
      <xs:enumeration value="1.2.752.129.2.1.3.1" />
      <xs:enumeration value="1.2.752.129.2.1.3.3" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="patientIdExtension">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{8}-\d{4}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="hsaId">
    <xs:complexContent>
      <xs:restriction base="iso:II">
        <xs:attribute name="root" type="iso:Uid" use="required"
          fixed="1.2.752.129.2.1.4.1" />
        <xs:attribute name="extension" type="xs:string"
          use="required" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="arbetsplatsKod">
    <xs:complexContent>
      <xs:restriction base="iso:II">
        <xs:attribute name="root" type="iso:Uid" use="required"
          fixed="1.2.752.29.4.71" />
        <xs:attribute name="extension" type="xs:string"
          use="required" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="patientType">
    <xs:sequence>
      <xs:element name="person-id" type="personId" />
      <xs:element name="fornamn" type="xs:string" maxOccurs="unbounded" />
      <xs:element name="efternamn" type="xs:string" />
      <xs:element name="postadress" type="xs:string" />
      <xs:element name="postnummer" type="xs:string" />
      <xs:element name="postort" type="xs:string" />

      <xs:any namespace="##other" processContents="lax"
        minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="vardkontaktType">
    <xs:sequence>
      <xs:element name="vardkontakttyp" type="iso:CD" />
      <xs:element name="idKontroll" type="iso:CD" />

      <xs:any namespace="##other" processContents="lax"
        minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="aktivitetType">
    <xs:sequence>
      <xs:element name="aktivitetsid" type="iso:II"
        minOccurs="0" />
      <xs:element name="aktivitetskod" type="iso:CD" />
      <xs:element name="ostruktureradtid" type="xs:string"
        minOccurs="0" />
      <xs:element name="beskrivning" type="xs:string"
        minOccurs="0" />
      <xs:element name="aktivitetsstatus" type="iso:CD"
        minOccurs="0" />
      <xs:element name="plats" type="xs:string" minOccurs="0" />
      <xs:element name="metod" type="iso:CD" minOccurs="0" />
      <xs:element name="forekomst" type="xs:boolean"
        minOccurs="0" />

      <xs:any namespace="##other" processContents="lax"
        minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="observationType">
    <xs:sequence>
      <xs:element name="observationsid" type="iso:II"
        minOccurs="0" />
      <xs:element name="observationskod" type="iso:CD" />
      <xs:element name="forekomst" type="xs:boolean"
        minOccurs="0" />
      <xs:element name="lateralitet" type="iso:CD" minOccurs="0" />
      <xs:element name="varde" type="iso:PQ" minOccurs="0" />
      <xs:element name="beskrivning" type="xs:string"
        minOccurs="0" />
      <xs:element name="observationstid" type="date"
        minOccurs="0" maxOccurs="1" />
      <xs:element name="observationsperiod" type="partialDateInterval"
        minOccurs="0" maxOccurs="1" />
      <xs:any namespace="##other" processContents="lax"
        minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="rekommendationType">
    <xs:sequence>
      <xs:element name="rekommendationskod" type="iso:CD" />
      <xs:element name="beskrivning" type="xs:string"
        minOccurs="0" />
      <xs:element name="varde" type="iso:CD" minOccurs="0"
        maxOccurs="16" />
      <xs:element name="boolean_varde" type="xs:boolean"
        minOccurs="0" />
      <xs:any namespace="##other" processContents="lax"
        minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="bilagaType">
    <xs:sequence>
      <xs:element name="bilagekod" type="iso:CD" />
      <xs:element name="forekomst" type="xs:boolean" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="hosPersonalType">
    <xs:sequence>
      <xs:element name="personal-id" type="iso:II">
        <xs:annotation>
          <xs:documentation>HSA-id, o.i.d för HSA-id är
            1.2.752.129.2.1.4.1
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="fullstandigtNamn" type="xs:string"
        minOccurs="0">
        <xs:annotation>
          <xs:documentation>Förnamn + efternamn sammanslaget.
            Är tomt om
            personen har en skyddad identitet.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="befattning" type="iso:CD"
        minOccurs="0" maxOccurs="unbounded" />
        
      <xs:element name="enhet" type="enhetType" />
      <xs:element name="specialitet" type="iso:CD" minOccurs="0"
        maxOccurs="unbounded" />

      <xs:any namespace="##other" processContents="lax"
        minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="enhetType">
    <xs:sequence>
      <xs:element name="enhets-id" type="hsaId">
        <xs:annotation>
          <xs:documentation>HSA-id, o.i.d för HSA-id är
            1.2.752.129.2.1.4.1
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="arbetsplatskod" type="arbetsplatsKod"
        minOccurs="0">
        <xs:annotation>
          <xs:documentation>o.i.d för arbetsplatskod är 1.2.752.29.4.71
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="enhetsnamn" type="xs:string" />
      <xs:element name="postadress" type="xs:string"
        minOccurs="0" />
      <xs:element name="postnummer" type="xs:string"
        minOccurs="0" />
      <xs:element name="postort" type="xs:string" minOccurs="0" />
      <xs:element name="telefonnummer" type="xs:string"
        minOccurs="0" />
      <xs:element name="epost" type="xs:string" minOccurs="0" />
      <xs:element name="vardgivare" type="vardgivareType"
        minOccurs="0" />

      <xs:any namespace="##other" processContents="lax"
        minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="vardgivareType">
    <xs:sequence>
      <xs:element name="vardgivare-id" type="hsaId">
        <xs:annotation>
          <xs:documentation>HSA-id, o.i.d för HSA-id är
            1.2.752.129.2.1.4.1
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="vardgivarnamn" type="xs:string" />

      <xs:any namespace="##other" processContents="lax"
        minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="observationAktivitetRelationType">
    <xs:sequence>
      <xs:element name="observationsid" type="iso:II" />
      <xs:element name="aktivitetsid" type="iso:II" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="date">
    <xs:annotation>
      <xs:documentation>
        Date value is a string with the format
        &#34;YYYY-MM-DD&#34; that
        conforms to the constrained ISO 8601.
        Time
        and timezone precision is not required.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern
        value="[1-2][0-9]{3,3}-((0[1-9])|(1[0-2]))-((0[1-9])|([1-2][0-9])|(3[0-1]))" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="dateTime">
    <xs:annotation>
      <xs:documentation>
        DateTime value is a string with the format
        &#34;YYYY-MM-DDThh:mm:ss&#34;
        that conforms to the constrained
        ISO
        8601.
        Fraction of seconds and timezone precision is not
        required.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern
        value="[1-2][0-9]{3,3}-((0[1-9])|(1[0-2]))-((0[1-9])|([1-2][0-9])|(3[0-1]))T(([0-1][0-9])|(2[0-3])):([0-5][0-9]):([0-5][0-9])" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="partialDate">
    <xs:annotation>
      <xs:documentation>
        PartialDate value is a string with the format
        &#34;YYYY[-MM[-DD]]&#34; that
        conforms to the constrained ISO
        8601.
        In
        contrast to the date type, this type also allows for
        year-only and
        year-and-month values.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern
        value="[1-2][0-9]{3,3}(-((0[1-9])|(1[0-2]))(-((0[1-9])|([1-2][0-9])|(3[0-1])))?)?" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="dateInterval">
    <xs:sequence>
      <xs:element name="from" type="date" minOccurs="0" />
      <xs:element name="tom" type="date" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="partialDateInterval">
    <xs:sequence>
      <xs:element name="from" type="partialDate" minOccurs="0" />
      <xs:element name="tom" type="partialDate" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== ViktorEdfalk/common/ts-diabetes/src/test/resources/scenarios/transport/valid-diabetes-typ2-kost.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:utlatande xmlns:p="urn:riv:clinicalprocess:healthcond:certificate:1"
  xmlns:p1="urn:iso:21090:dt:1"
  xmlns:p2="urn:riv:clinicalprocess:healthcond:certificate:ts-diabetes:1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:riv:clinicalprocess:healthcond:certificate:1 ../../../../main/resources/schemas/transport_model.xsd ">

  <p:utlatande-id root="1.2.752.129.2.1.2.1" extension="987654321" />

  <p:typAvUtlatande code="ts-diabetes"
    codeSystem="f6fb361a-e31d-48b8-8657-99b63912dd9b" codeSystemName="kv_utlåtandetyp_intyg" />

  <p:signeringsdatum>2013-08-12T15:57:00</p:signeringsdatum>

  <p:patient>
    <p:person-id extension="19121212-1212" root="1.2.752.129.2.1.3.1" />
    <p:fornamn>Johnny</p:fornamn>
    <p:efternamn>Appleseed</p:efternamn>
    <p:postadress>Testvägen 12</p:postadress>
    <p:postnummer>123456</p:postnummer>
    <p:postort>Testort</p:postort>
  </p:patient>

  <p:skapadAv>
    <p:personal-id extension="SE0000000000-1333" root="1.2.752.129.2.1.4.1" />
    <p:fullstandigtNamn>Doktor Thompson</p:fullstandigtNamn>
    <p:enhet>
      <p:enhets-id extension="SE0000000000-1337" root="1.2.752.129.2.1.4.1" />
      <p:enhetsnamn>Vårdenhet Väst</p:enhetsnamn>
      <p:postadress>Enhetsvägen 12</p:postadress>
      <p:postnummer>54321</p:postnummer>
      <p:postort>Tumba</p:postort>
      <p:telefonnummer>08-1337</p:telefonnummer>
      <p:vardgivare>
        <p:vardgivare-id root="1.2.752.129.2.1.4.1"
          extension="SE0000000000-HAHAHHSAA" />
        <p:vardgivarnamn>Vårdgivarnamn</p:vardgivarnamn>
      </p:vardgivare>
    </p:enhet>
  </p:skapadAv>

  <p:vardkontakt>
    <p:vardkontakttyp code="5880005" codeSystem="1.2.752.116.2.1.1.1"
      codeSystemName="SNOMED-CT" />
    <p:idKontroll code="IDK6" codeSystem="e7cc8f30-a353-4c42-b17a-a189b6876647"
      codeSystemName="kv_id_kontroll" />
  </p:vardkontakt>

  <!-- AKTIVITETER -->
  <!-- Aktiviteter end -->

  <!-- Rekommendation begin -->
  <p:rekommendation>
    <p:rekommendationskod code="REK8"
      codeSystem="5a931b99-bda8-4f1e-8a6d-6f8a3f40a459" codeSystemName="kv_rekommendation_intyg" />
    <p2:varde code="VAR12" codeSystem="5a931b99-bda8-4f1e-8a6d-6f8a3f40a459"
      codeSystemName="kv_rekommendation_intyg" />
  </p:rekommendation>
  <!-- Rekommendation end -->

  <!-- Observationer begins -->
  
  <p:observation>
   <p:observationskod code="E11" codeSystem="1.2.752.116.1.1.1.1.1" codeSystemName="ICD-10" />
    <p:observationsperiod>
      <p:from>2012</p:from>
    </p:observationsperiod>
    <p:forekomst>true</p:forekomst>
  </p:observation>
  
  <p:observation>
    <p:observationskod code="170745003" codeSystem="1.2.752.116.2.1.1.1"
      codeSystemName="SNOMED-CT" />
    <p:forekomst>true</p:forekomst>
  </p:observation>
  
  <p:observation>
   <p:observationskod code="OBS19" codeSystem="335d4bed-7e1d-4f81-ae7d-b39b266ef1a3" codeSystemName="kv_observationer_intyg" />
    <p:forekomst>false</p:forekomst>
  </p:observation>
  
  <p:observation>
   <p:observationskod code="OBS20" codeSystem="335d4bed-7e1d-4f81-ae7d-b39b266ef1a3"
      codeSystemName="kv_observationer_intyg" />
    <p:forekomst>false</p:forekomst>
  </p:observation>
  <!-- Observationer ends -->

  <!-- ObservationAktivitetRelation begin -->
  <!-- ObservationAktivitetRelation ends -->

  <p2:intygAvser code="IAV12" codeSystem="24c41b8d-258a-46bf-a08a-b90738b28770"
    codeSystemName="kv_intyget_avser" />

  <p2:bilaga>
    <p2:bilagetyp code="BIL1" codeSystem="80595600-7477-4a6c-baeb-d2439e86b8bc"
      codeSystemName="kv_bilaga" />
    <p2:forekomst>true</p2:forekomst>  
  </p2:bilaga>
  
  <p2:utgava>06</p2:utgava>
  <p2:version>02</p2:version>
  
</p:utlatande>

=== ViktorEdfalk/common/ts-diabetes/src/test/resources/scenarios/transport/valid-minimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:utlatande xmlns:p="urn:riv:clinicalprocess:healthcond:certificate:1"
  xmlns:p1="urn:iso:21090:dt:1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:riv:clinicalprocess:healthcond:certificate:1 ../../../../main/resources/schemas/transport_model.xsd ">

  <p:utlatande-id root="1.2.752.129.2.1.2.1" extension="987654321" />

  <p:typAvUtlatande code="TSTRK1031 (U06, V02)"
    codeSystem="f6fb361a-e31d-48b8-8657-99b63912dd9b" codeSystemName="kv_utlåtandetyp_intyg" />

  <p:signeringsdatum>2013-08-12T15:57:00</p:signeringsdatum>

  <p:intygAvser code="IAV12" codeSystem="todo"
    codeSystemName="kv_intygavser_intyg" />

  <p:patient>
    <p:person-id extension="19121212-1212" root="1.2.752.129.2.1.3.1" />
    <p:fornamn>Johnny</p:fornamn>
    <p:efternamn>Appleseed</p:efternamn>
    <p:postadress>Testvägen 12</p:postadress>
    <p:postnummer>123456</p:postnummer>
    <p:postort>Testort</p:postort>
  </p:patient>

  <p:skapadAv>
    <p:personal-id extension="SE0000000000-1333" root="1.2.752.129.2.1.4.1" />
    <p:fullstandigtNamn>Doktor Thompson</p:fullstandigtNamn>
    <p:enhet>
      <p:enhets-id extension="SE0000000000-1337" root="1.2.752.129.2.1.4.1" />
      <p:enhetsnamn>Vårdenhet Väst</p:enhetsnamn>
      <p:postadress>Enhetsvägen 12</p:postadress>
      <p:postnummer>54321</p:postnummer>
      <p:postort>Tumba</p:postort>
      <p:telefonnummer>08-1337</p:telefonnummer>
      <p:vardgivare>
        <p:vardgivare-id root="1.2.752.129.2.1.4.1"
          extension="SE0000000000-HAHAHHSAA" />
        <p:vardgivarnamn>Vårdgivarnamn</p:vardgivarnamn>
      </p:vardgivare>
    </p:enhet>
  </p:skapadAv>

  <p:vardkontakt>
    <p:vardkontakttyp code="5880005" codeSystem="1.2.752.116.2.1.1.1"
      codeSystemName="SNOMED-CT" />
    <p:idKontroll code="IDK6" codeSystem="???"
      codeSystemName="kv_id_kontroll" />
  </p:vardkontakt>

  <!-- AKTIVITETER -->
  <!-- Aktiviteter end -->

  <!-- Rekommendation begin -->
  <p:rekommendation>
    <p:rekommendationskod code="REK8"
      codeSystem="5a931b99-bda8-4f1e-8a6d-6f8a3f40a459" codeSystemName="kv_rekommendation_intyg" />
    <p:korkortsbehorighet code="VAR13" codeSystem="5a931b99-bda8-4f1e-8a6d-6f8a3f40a459"
      codeSystemName="kv_rekommendation_intyg" />
  </p:rekommendation>
  <!-- Rekommendation end -->

  <!-- Observationer begins -->
  
  <p:observation>
   <p:observationskod code="E11" codeSystem="1.2.752.116.1.1.1.1.1" codeSystemName="ICD-10" />
    <p:forekomst>true</p:forekomst>
    <p:observationsperiod>
      <p:from>2012</p:from>
    </p:observationsperiod>
  </p:observation>
  
  <p:observation>
    <p:observationskod code="170745003" codeSystem="1.2.752.116.2.1.1.1"
      codeSystemName="SNOMED-CT" />
    <p:forekomst>true</p:forekomst>
  </p:observation>
  
  <p:observation>
   <p:observationskod code="OBS19" codeSystem="to-come" codeSystemName="kv_observationer_intyg" />
    <p:forekomst>false</p:forekomst>
  </p:observation>
  
  <p:observation>
   <p:observationskod code="OBS20" codeSystem="to-come"
      codeSystemName="kv_observationer_intyg" />
    <p:forekomst>false</p:forekomst>
  </p:observation>
  <!-- Observationer ends -->

  <!-- ObservationAktivitetRelation begin -->
  <!-- ObservationAktivitetRelation ends -->
  
  <p:bilaga>
    <p:bilagetyp code="BIL1" codeSystem="???"
      codeSystemName="kv_bilaga" />
    <p:forekomst>true</p:forekomst>  
  </p:bilaga>
  
  <p:utgava>06</p:utgava>
  <p:version>02</p:version>
  
</p:utlatande>
